version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    working_dir: /app
    command: sh -c "npx prisma generate && npx prisma db push && yarn dev -H 0.0.0.0"
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
    volumes:
      - .:/app
      # Keep container-managed node_modules separate from host
      - /app/node_modules
      - /app/.next
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db-data: {}
