version: "3.9"

services:
  app:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "corepack enable && yarn install --frozen-lockfile && yarn dev -H 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - .:/app
      # Keep container-managed node_modules separate from host
      - /app/node_modules
      - /app/.next
    # To add a database later, define another service and add depends_on here.
